spring:
  application:
    name: ttsx-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: ttsx-prod
    gateway:
      globalcors:  #全局跨域处理
        cors-configurations:
          '[/**]':
            allowedMethods: "*"
            allowedHeaders: "*"
            #要注意的是，当 Access-Control-Allow-Credentials 的值为 true 时，Access-Control-Allow-Origin 的值只能是请求的 Origin，不能是 *
            allowedOrigins: "*"
      #            allowCredentials: true   #并且允许携带身份凭证
      routes:
        - id: ttsx-order-addr
          uri: lb://ttsx-order
          predicates:
           - Path=/addr/**

        - id: ttsx-foods
          uri: lb://ttsx-foods
          predicates:
           - Path=/goods/**
          filters:
#           - RewritePath=/foods/(?<segment>.*), /$\{segment}
        - id: ttsx-order
          uri: lb://ttsx-order
          predicates:
            - Path=/order/**

        - id: ttsx-order-cart
          uri: lb://ttsx-order
          predicates:
            - Path=/cart/**
          filters:
#            - RewritePath=/foods/(?<segment>.*), /$\{segment}
        - id: ttsx-index
          uri: lb://ttsx-index
          predicates:
            - Path=/index/**
          filters:
            - RewritePath=/index/(?<segment>.*), /$\{segment}
        - id: ttsx-user
          uri: lb://ttsx-user
          predicates:
            - Path=/user/**


server:
  port: 20001  #网关端口

management:
  endpoints:
    web:
      exposure:
        include: "*"    # 暴露gateway端点，* 是暴露全部端点
  endpoint:
    gateway:
      enabled: true # default value